export type MarketplaceCity = { slug: string; label: string };

export const MARKETPLACE_CITIES: readonly MarketplaceCity[] = [
  { slug: "new-york-city", label: "New York, NY" },
  { slug: "los-angeles", label: "Los Angeles, CA" },
  { slug: "chicago", label: "Chicago, IL" },
  { slug: "houston", label: "Houston, TX" },
  { slug: "phoenix", label: "Phoenix, AZ" },
  { slug: "philadelphia", label: "Philadelphia, PA" },
  { slug: "san-antonio", label: "San Antonio, TX" },
  { slug: "san-diego", label: "San Diego, CA" },
  { slug: "dallas", label: "Dallas, TX" },
  { slug: "san-jose", label: "San Jose, CA" },
  { slug: "austin", label: "Austin, TX" },
  { slug: "jacksonville", label: "Jacksonville, FL" },
  { slug: "fort-worth", label: "Fort Worth, TX" },
  { slug: "columbus", label: "Columbus, OH" },
  { slug: "charlotte", label: "Charlotte, NC" },
  { slug: "san-francisco", label: "San Francisco, CA" },
  { slug: "indianapolis", label: "Indianapolis, IN" },
  { slug: "seattle", label: "Seattle, WA" },
  { slug: "denver", label: "Denver, CO" },
  { slug: "washington-dc", label: "Washington, DC" },
  { slug: "boston", label: "Boston, MA" },
  { slug: "el-paso", label: "El Paso, TX" },
  { slug: "nashville", label: "Nashville, TN" },
  { slug: "detroit", label: "Detroit, MI" },
  { slug: "oklahoma-city", label: "Oklahoma City, OK" },
  { slug: "portland", label: "Portland, OR" },
  { slug: "las-vegas", label: "Las Vegas, NV" },
  { slug: "memphis", label: "Memphis, TN" },
  { slug: "louisville", label: "Louisville, KY" },
  { slug: "baltimore", label: "Baltimore, MD" },
  { slug: "milwaukee", label: "Milwaukee, WI" },
  { slug: "albuquerque", label: "Albuquerque, NM" },
  { slug: "tucson", label: "Tucson, AZ" },
  { slug: "fresno", label: "Fresno, CA" },
  { slug: "sacramento", label: "Sacramento, CA" },
  { slug: "mesa", label: "Mesa, AZ" },
  { slug: "kansas-city", label: "Kansas City, MO" },
  { slug: "atlanta", label: "Atlanta, GA" },
  { slug: "omaha", label: "Omaha, NE" },
  { slug: "colorado-springs", label: "Colorado Springs, CO" },
  { slug: "raleigh", label: "Raleigh, NC" },
  { slug: "miami", label: "Miami, FL" },
  { slug: "virginia-beach", label: "Virginia Beach, VA" },
  { slug: "oakland", label: "Oakland, CA" },
  { slug: "minneapolis", label: "Minneapolis, MN" },
  { slug: "tulsa", label: "Tulsa, OK" },
  { slug: "arlington", label: "Arlington, TX" },
  { slug: "new-orleans", label: "New Orleans, LA" },
  { slug: "wichita", label: "Wichita, KS" },
  { slug: "cleveland", label: "Cleveland, OH" },
  { slug: "tampa", label: "Tampa, FL" },
  { slug: "bakersfield", label: "Bakersfield, CA" },
  { slug: "aurora", label: "Aurora, CO" },
  { slug: "anaheim", label: "Anaheim, CA" },
  { slug: "honolulu", label: "Honolulu, HI" },
  { slug: "santa-ana", label: "Santa Ana, CA" },
  { slug: "riverside", label: "Riverside, CA" },
  { slug: "corpus-christi", label: "Corpus Christi, TX" },
  { slug: "lexington", label: "Lexington, KY" },
  { slug: "stockton", label: "Stockton, CA" },
  { slug: "st-louis", label: "St. Louis, MO" },
  { slug: "saint-paul", label: "Saint Paul, MN" },
  { slug: "henderson", label: "Henderson, NV" },
  { slug: "pittsburgh", label: "Pittsburgh, PA" },
  { slug: "cincinnati", label: "Cincinnati, OH" },
  { slug: "anchorage", label: "Anchorage, AK" },
  { slug: "irvine", label: "Irvine, CA" },
  { slug: "newark", label: "Newark, NJ" },
  { slug: "lincoln", label: "Lincoln, NE" },
  { slug: "orlando", label: "Orlando, FL" },
  { slug: "durham", label: "Durham, NC" },
  { slug: "jersey-city", label: "Jersey City, NJ" },
  { slug: "laredo", label: "Laredo, TX" },
  { slug: "fort-wayne", label: "Fort Wayne, IN" },
  { slug: "charleston", label: "Charleston, SC" },
  { slug: "birmingham", label: "Birmingham, AL" },
  { slug: "scottsdale", label: "Scottsdale, AZ" },
  { slug: "reno", label: "Reno, NV" },
  { slug: "boise", label: "Boise, ID" },
  { slug: "baton-rouge", label: "Baton Rouge, LA" },
  { slug: "fayetteville", label: "Fayetteville, NC" },
  { slug: "shreveport", label: "Shreveport, LA" },
  { slug: "des-moines", label: "Des Moines, IA" },
  { slug: "richmond", label: "Richmond, VA" },
  { slug: "little-rock", label: "Little Rock, AR" },
  { slug: "tallahassee", label: "Tallahassee, FL" },
  { slug: "knoxville", label: "Knoxville, TN" },
  { slug: "providence", label: "Providence, RI" },
  { slug: "salt-lake-city", label: "Salt Lake City, UT" },
  { slug: "tempe", label: "Tempe, AZ" },
  { slug: "worcester", label: "Worcester, MA" },
  { slug: "huntsville", label: "Huntsville, AL" },
  { slug: "sioux-falls", label: "Sioux Falls, SD" },
  { slug: "grand-rapids", label: "Grand Rapids, MI" },
  { slug: "mobile", label: "Mobile, AL" },
  { slug: "burlington", label: "Burlington, VT" },
  { slug: "manchester", label: "Manchester, NH" },
  { slug: "hartford", label: "Hartford, CT" },
  { slug: "billings", label: "Billings, MT" },
  { slug: "fargo", label: "Fargo, ND" },
  { slug: "casper", label: "Casper, WY" },
  { slug: "cheyenne", label: "Cheyenne, WY" },
  { slug: "savannah", label: "Savannah, GA" },
  { slug: "augusta", label: "Augusta, GA" },
  { slug: "montgomery", label: "Montgomery, AL" },
  { slug: "madison", label: "Madison, WI" },
  { slug: "greenville-sc", label: "Greenville, SC" },
  { slug: "gulfport", label: "Gulfport, MS" },
  { slug: "jackson", label: "Jackson, MS" },
  { slug: "portland-me", label: "Portland, ME" },
  { slug: "columbia-sc", label: "Columbia, SC" },
  { slug: "springfield-mo", label: "Springfield, MO" },
  { slug: "springfield-il", label: "Springfield, IL" },
  { slug: "springfield-ma", label: "Springfield, MA" },
  { slug: "albany", label: "Albany, NY" },
  { slug: "buffalo", label: "Buffalo, NY" },
  { slug: "rochester", label: "Rochester, NY" },
  { slug: "syracuse", label: "Syracuse, NY" },
  { slug: "allentown", label: "Allentown, PA" },
  { slug: "grand-junction", label: "Grand Junction, CO" },
  { slug: "fort-collins", label: "Fort Collins, CO" },
  { slug: "spokane", label: "Spokane, WA" },
  { slug: "tacoma", label: "Tacoma, WA" },
  { slug: "eugene", label: "Eugene, OR" },
  { slug: "salem", label: "Salem, OR" },
  { slug: "bozeman", label: "Bozeman, MT" },
  { slug: "rapid-city", label: "Rapid City, SD" },
  { slug: "cedar-rapids", label: "Cedar Rapids, IA" },
  { slug: "quad-cities", label: "Quad Cities, IA/IL" },
  { slug: "peoria-il", label: "Peoria, IL" },
  { slug: "evansville", label: "Evansville, IN" },
  { slug: "south-bend", label: "South Bend, IN" },
  { slug: "bowling-green", label: "Bowling Green, KY" },
  { slug: "chattanooga", label: "Chattanooga, TN" },
  { slug: "clarksville", label: "Clarksville, TN" },
  { slug: "asheville", label: "Asheville, NC" },
  { slug: "wilmington", label: "Wilmington, NC" },
  { slug: "greensboro", label: "Greensboro, NC" },
  { slug: "winston-salem", label: "Winston-Salem, NC" },
  { slug: "myrtle-beach", label: "Myrtle Beach, SC" },
  { slug: "macon", label: "Macon, GA" },
  { slug: "pensacola", label: "Pensacola, FL" },
  { slug: "gainesville", label: "Gainesville, FL" },
  { slug: "fort-myers", label: "Fort Myers, FL" },
  { slug: "sarasota", label: "Sarasota, FL" },
  { slug: "daytona-beach", label: "Daytona Beach, FL" },
  { slug: "chandler", label: "Chandler, AZ" },
  { slug: "gilbert", label: "Gilbert, AZ" },
  { slug: "glendale-az", label: "Glendale, AZ" },
  { slug: "peoria-az", label: "Peoria, AZ" },
  { slug: "surprise", label: "Surprise, AZ" },
  { slug: "flagstaff", label: "Flagstaff, AZ" },
  { slug: "yuma", label: "Yuma, AZ" },
  { slug: "lake-havasu-city", label: "Lake Havasu City, AZ" },
  { slug: "oxnard", label: "Oxnard, CA" },
  { slug: "thousand-oaks", label: "Thousand Oaks, CA" },
  { slug: "simi-valley", label: "Simi Valley, CA" },
  { slug: "ventura", label: "Ventura, CA" },
  { slug: "santa-barbara", label: "Santa Barbara, CA" },
  { slug: "santa-maria", label: "Santa Maria, CA" },
  { slug: "san-luis-obispo", label: "San Luis Obispo, CA" },
  { slug: "salinas", label: "Salinas, CA" },
  { slug: "monterey", label: "Monterey, CA" },
  { slug: "santa-cruz", label: "Santa Cruz, CA" },
  { slug: "modesto", label: "Modesto, CA" },
  { slug: "merced", label: "Merced, CA" },
  { slug: "visalia", label: "Visalia, CA" },
  { slug: "hanford", label: "Hanford, CA" },
  { slug: "redding", label: "Redding, CA" },
  { slug: "chico", label: "Chico, CA" },
  { slug: "eureka", label: "Eureka, CA" },
  { slug: "greeley", label: "Greeley, CO" },
  { slug: "boulder", label: "Boulder, CO" },
  { slug: "pueblo", label: "Pueblo, CO" },
  { slug: "bridgeport", label: "Bridgeport, CT" },
  { slug: "new-haven", label: "New Haven, CT" },
  { slug: "stamford", label: "Stamford, CT" },
  { slug: "waterbury", label: "Waterbury, CT" },
  { slug: "danbury", label: "Danbury, CT" },
  { slug: "wilmington-de", label: "Wilmington, DE" },
  { slug: "dover", label: "Dover, DE" },
  { slug: "ocala", label: "Ocala, FL" },
  { slug: "panama-city", label: "Panama City, FL" },
  { slug: "st-augustine", label: "St. Augustine, FL" },
  { slug: "palm-bay", label: "Palm Bay, FL" },
  { slug: "melbourne", label: "Melbourne, FL" },
  { slug: "port-st-lucie", label: "Port St. Lucie, FL" },
  { slug: "fort-pierce", label: "Fort Pierce, FL" },
  { slug: "lakeland", label: "Lakeland, FL" },
  { slug: "winter-haven", label: "Winter Haven, FL" },
  { slug: "bradenton", label: "Bradenton, FL" },
  { slug: "naples", label: "Naples, FL" },
  { slug: "fort-walton-beach", label: "Fort Walton Beach, FL" },
  { slug: "athens-ga", label: "Athens, GA" },
  { slug: "valdosta", label: "Valdosta, GA" },
  { slug: "albany-ga", label: "Albany, GA" },
  { slug: "hilo", label: "Hilo, HI" },
  { slug: "kahului", label: "Kahului, HI" },
  { slug: "coeur-d-alene", label: "Coeur d'Alene, ID" },
  { slug: "idaho-falls", label: "Idaho Falls, ID" },
  { slug: "pocatello", label: "Pocatello, ID" },
  { slug: "twin-falls", label: "Twin Falls, ID" },
  { slug: "rockford", label: "Rockford, IL" },
  { slug: "joliet", label: "Joliet, IL" },
  { slug: "naperville", label: "Naperville, IL" },
  { slug: "bloomington-il", label: "Bloomington, IL" },
  { slug: "champaign", label: "Champaign, IL" },
  { slug: "decatur-il", label: "Decatur, IL" },
  { slug: "muncie", label: "Muncie, IN" },
  { slug: "terre-haute", label: "Terre Haute, IN" },
  { slug: "lafayette-in", label: "Lafayette, IN" },
  { slug: "anderson-in", label: "Anderson, IN" },
  { slug: "ames", label: "Ames, IA" },
  { slug: "iowa-city", label: "Iowa City, IA" },
  { slug: "waterloo-ia", label: "Waterloo, IA" },
  { slug: "dubuque", label: "Dubuque, IA" },
  { slug: "lawrence-ks", label: "Lawrence, KS" },
  { slug: "manhattan-ks", label: "Manhattan, KS" },
  { slug: "topeka", label: "Topeka, KS" },
  { slug: "salina-ks", label: "Salina, KS" },
  { slug: "hutchinson", label: "Hutchinson, KS" },
  { slug: "owensboro", label: "Owensboro, KY" },
  { slug: "paducah", label: "Paducah, KY" },
  { slug: "lake-charles", label: "Lake Charles, LA" },
  { slug: "lafayette-la", label: "Lafayette, LA" },
  { slug: "houma", label: "Houma, LA" },
  { slug: "monroe-la", label: "Monroe, LA" },
  { slug: "alexandria-la", label: "Alexandria, LA" },
  { slug: "bangor", label: "Bangor, ME" },
  { slug: "lewiston-me", label: "Lewiston, ME" },
  { slug: "annapolis", label: "Annapolis, MD" },
  { slug: "frederick", label: "Frederick, MD" },
  { slug: "salisbury-md", label: "Salisbury, MD" },
  { slug: "hagerstown", label: "Hagerstown, MD" },
  { slug: "lowell", label: "Lowell, MA" },
  { slug: "cambridge-ma", label: "Cambridge, MA" },
  { slug: "brockton", label: "Brockton, MA" },
  { slug: "quincy-ma", label: "Quincy, MA" },
  { slug: "new-bedford", label: "New Bedford, MA" },
  { slug: "fall-river", label: "Fall River, MA" },
  { slug: "ann-arbor", label: "Ann Arbor, MI" },
  { slug: "lansing", label: "Lansing, MI" },
  { slug: "flint", label: "Flint, MI" },
  { slug: "kalamazoo", label: "Kalamazoo, MI" },
  { slug: "saginaw", label: "Saginaw, MI" },
  { slug: "muskegon", label: "Muskegon, MI" },
  { slug: "traverse-city", label: "Traverse City, MI" },
  { slug: "duluth", label: "Duluth, MN" },
  { slug: "rochester-mn", label: "Rochester, MN" },
  { slug: "st-cloud", label: "St. Cloud, MN" },
  { slug: "mankato", label: "Mankato, MN" },
  { slug: "hattiesburg", label: "Hattiesburg, MS" },
  { slug: "meridian", label: "Meridian, MS" },
  { slug: "biloxi", label: "Biloxi, MS" },
  { slug: "columbia-mo", label: "Columbia, MO" },
  { slug: "st-joseph", label: "St. Joseph, MO" },
  { slug: "joplin", label: "Joplin, MO" },
  { slug: "missoula", label: "Missoula, MT" },
  { slug: "great-falls", label: "Great Falls, MT" },
  { slug: "grand-island", label: "Grand Island, NE" },
  { slug: "kearney", label: "Kearney, NE" },
  { slug: "carson-city", label: "Carson City, NV" },
  { slug: "elko", label: "Elko, NV" },
  { slug: "nashua", label: "Nashua, NH" },
  { slug: "concord-nh", label: "Concord, NH" },
  { slug: "elizabeth-nj", label: "Elizabeth, NJ" },
  { slug: "paterson", label: "Paterson, NJ" },
  { slug: "trenton", label: "Trenton, NJ" },
  { slug: "atlantic-city", label: "Atlantic City, NJ" },
  { slug: "las-cruces", label: "Las Cruces, NM" },
  { slug: "santa-fe", label: "Santa Fe, NM" },
  { slug: "roswell", label: "Roswell, NM" },
  { slug: "farmington-nm", label: "Farmington, NM" },
  { slug: "yonkers", label: "Yonkers, NY" },
  { slug: "utica", label: "Utica, NY" },
  { slug: "binghamton", label: "Binghamton, NY" },
  { slug: "wilmington-nc", label: "Wilmington, NC" },
  { slug: "jacksonville-nc", label: "Jacksonville, NC" },
  { slug: "gastonia", label: "Gastonia, NC" },
  { slug: "high-point", label: "High Point, NC" },
  { slug: "grand-forks", label: "Grand Forks, ND" },
  { slug: "minot", label: "Minot, ND" },
  { slug: "akron", label: "Akron, OH" },
  { slug: "dayton", label: "Dayton, OH" },
  { slug: "toledo", label: "Toledo, OH" },
  { slug: "youngstown", label: "Youngstown, OH" },
  { slug: "canton-oh", label: "Canton, OH" },
  { slug: "norman", label: "Norman, OK" },
  { slug: "broken-arrow", label: "Broken Arrow, OK" },
  { slug: "edmond", label: "Edmond, OK" },
  { slug: "lawton", label: "Lawton, OK" },
  { slug: "bend", label: "Bend, OR" },
  { slug: "medford", label: "Medford, OR" },
  { slug: "corvallis", label: "Corvallis, OR" },
  { slug: "erie", label: "Erie, PA" },
  { slug: "reading-pa", label: "Reading, PA" },
  { slug: "scranton", label: "Scranton, PA" },
  { slug: "lancaster-pa", label: "Lancaster, PA" },
  { slug: "harrisburg", label: "Harrisburg, PA" },
  { slug: "warwick", label: "Warwick, RI" },
  { slug: "cranston", label: "Cranston, RI" },
  { slug: "spartanburg", label: "Spartanburg, SC" },
  { slug: "rock-hill", label: "Rock Hill, SC" },
  { slug: "rapid-city-sd", label: "Rapid City, SD" },
  { slug: "murfreesboro", label: "Murfreesboro, TN" },
  { slug: "jackson-tn", label: "Jackson, TN" },
  { slug: "johnson-city", label: "Johnson City, TN" },
  { slug: "plano", label: "Plano, TX" },
  { slug: "lubbock", label: "Lubbock, TX" },
  { slug: "irving", label: "Irving, TX" },
  { slug: "garland", label: "Garland, TX" },
  { slug: "amarillo", label: "Amarillo, TX" },
  { slug: "brownsville", label: "Brownsville, TX" },
  { slug: "pasadena-tx", label: "Pasadena, TX" },
  { slug: "mesquite-tx", label: "Mesquite, TX" },
  { slug: "mcallen", label: "McAllen, TX" },
  { slug: "killeen", label: "Killeen, TX" },
  { slug: "denton", label: "Denton, TX" },
  { slug: "midland-tx", label: "Midland, TX" },
  { slug: "odessa-tx", label: "Odessa, TX" },
  { slug: "abilene", label: "Abilene, TX" },
  { slug: "beaumont", label: "Beaumont, TX" },
  { slug: "waco", label: "Waco, TX" },
  { slug: "tyler", label: "Tyler, TX" },
  { slug: "college-station", label: "College Station, TX" },
  { slug: "longview-tx", label: "Longview, TX" },
  { slug: "san-angelo", label: "San Angelo, TX" },
  { slug: "ogden", label: "Ogden, UT" },
  { slug: "provo", label: "Provo, UT" },
  { slug: "st-george", label: "St. George, UT" },
  { slug: "logan", label: "Logan, UT" },
  { slug: "vancouver-wa", label: "Vancouver, WA" },
  { slug: "bellevue", label: "Bellevue, WA" },
  { slug: "everett", label: "Everett, WA" },
  { slug: "yakima", label: "Yakima, WA" },
  { slug: "kennewick", label: "Kennewick, WA" },
  { slug: "bellingham", label: "Bellingham, WA" },
  { slug: "charleston-wv", label: "Charleston, WV" },
  { slug: "huntington-wv", label: "Huntington, WV" },
  { slug: "morgantown", label: "Morgantown, WV" },
  { slug: "green-bay", label: "Green Bay, WI" },
  { slug: "kenosha", label: "Kenosha, WI" },
  { slug: "racine", label: "Racine, WI" },
  { slug: "appleton", label: "Appleton, WI" },
  { slug: "eau-claire", label: "Eau Claire, WI" },
  { slug: "la-crosse", label: "La Crosse, WI" },
  { slug: "oshkosh", label: "Oshkosh, WI" },
  { slug: "janesville", label: "Janesville, WI" },
  { slug: "rock-springs", label: "Rock Springs, WY" },
  { slug: "gillette", label: "Gillette, WY" },
  { slug: "laramie", label: "Laramie, WY" }
] as const;
